---
- hosts: localhost
  become: yes
  gather_facts: true
  vars:
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USER') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASS') }}"
  tasks:
    - name: Log in to DockerHub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        reauthorize: yes
      register: login_out

    - name: Debug DockerHub login output
      debug:
        var: login_out
        
    - name: Build and push Docker image
      community.docker.docker_image:
        build:
          path: .
        name: docker.io/mallieswari/abc-technologies-cicd
        tag: latest
        push: yes
        source: build
      register: build_image_out

    - name: Debug Docker image build output
      debug:
        var: build_image_out

    - name: Start a Docker container
      community.docker.docker_container:
        name: abc-tech-container
        image: mallieswari/abc-technologies-cicd:latest
        state: started
        ports:
          - "8090:8080"
        # restart: yes
      register: build_container_out

    - name: Debug Docker container output
      debug:
        var: build_container_out
        
    - name: Create a Kubernetes Deployment from local file
      command: "kubectl --kubeconfig=/root/.kube/config apply -f deployment.yaml"
      register: kubectl_out

    - name: Debug Kubernetes deployment output
      debug:
        var: kubectl_out
