---
- hosts: localhost
  become: yes
  gather_facts: true
   vars:
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USER') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASS') }}"
  tasks:
    - name: Log in to DockerHub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
        reauthorize: yes
      register: login_out

    - debug:
        var: login_out
        
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: .
        name: docker.io/mallieswari/abc-technologies-cicd
        tag: latest
        push: true
        source: build
      register: build_image_out

    - debug:
        var: build_image_out

    - name: Start a container
      community.docker.docker_container:
        name: abc-tech-container
        image: mallieswari/abc-technologies-cicd
        state: started
        ports:
          - 8090:8080
        # restart: true
      register: build_container_out

    - debug:
        var: build_container_out
        
    - name: Create a Deployment by reading the definition from a local file
      command: "kubectl --kubeconfig=/root/.kube/config apply -f deployment.yaml"
      register: out
  
    - debug:
        var: out

 


